name: 🦖 .NET Checks

on:
  push:
    branches:
      - master
      - godot-4.*
  pull_request:
    branches-ignore:
      - godot3

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: ["6.0.x", "7.0.x"]

    name: .NET ${{ matrix.dotnet }}

    env:
      DemoProj: Dear ImGui for Godot Demo.csproj

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        id: dotnet_setup
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Create temporary global.json
        run: |
            echo '{"sdk":{"version": "${{ steps.dotnet_setup.outputs.dotnet-version }}"}}' > ./global.json

      - name: Modify .editorconfig
        run: |
          sed -i "s:dotnet_analyzer_diagnostic.severity = warning:dotnet_analyzer_diagnostic.severity = error:" .editorconfig

      - name: Restore dependencies
        run: dotnet restore

      - name: Format
        run: dotnet format --no-restore --verify-no-changes --verbosity detailed "${{ env.DemoProj }}" || (dotnet format --no-restore "${{ env.DemoProj }}" && git restore .editorconfig && git diff --color && exit 1)

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal
