name: 🤖 Godot Checks

on:
  push:
    branches:
      - master
      - godot-4.*
  pull_request:
    branches-ignore:
      - godot3

env:
  gdver: "4.0.3-stable"

jobs:
  export_game:
    name: Run with Godot
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Download Godot
        run: |
          cd $HOME
          wget https://github.com/godotengine/godot/releases/download/${{ env.gdver }}/Godot_v${{ env.gdver }}_mono_linux_x86_64.zip
          unzip Godot_v${{ env.gdver }}_mono_linux_x86_64.zip

      - name: Import resources and build
        run: |
          export gdbin=$HOME/Godot_v${{ env.gdver }}_mono_linux_x86_64/Godot_v${{ env.gdver }}_mono_linux.x86_64
          $gdbin --headless --build-solutions --quit

      # TODO: run tests with the exported binary
      - name: Test
        run: |
          export gdbin=$HOME/Godot_v${{ env.gdver }}_mono_linux_x86_64/Godot_v${{ env.gdver }}_mono_linux.x86_64
          $gdbin --headless --quit
