name: 🪟 MSVC

# TODO: upload dlls as artifact

on:
  push:
    branches-ignore:
      - godot3
  pull_request:
    branches-ignore:
      - godot3

env:
  VCPKG_ROOT: "${{ github.workspace }}/vcpkg"
  VCPKG_TARGET_TRIPLET: "x64-windows-static-md"

jobs:
  analyze:
    name: Build with SCons
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Setup scons
        run: |
          python -m pip install scons
          scons --version

      - name: Get vcpkg
        run: |
          git clone -n https://github.com/microsoft/vcpkg
          cd vcpkg
          git checkout 2023.04.15
          .\bootstrap-vcpkg.bat

      - name: vcpkg install
        run: |
          cd gdext
          ${{ env.VCPKG_ROOT }}\vcpkg install

      - name: Build debug
        run: |
          cd gdext
          scons debug_symbols=yes

      - name: Build release
        run: |
          cd gdext
          scons debug_symbols=yes target=template_release

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: gdext-windows
          path: gdext/proj/addons/imgui-godot-native/bin
