name: 🪟 MSVC

# TODO: upload dlls as artifact

on:
  push:
    branches-ignore:
      - godot3
  pull_request:
    branches-ignore:
      - godot3

env:
  VCPKG_ROOT: "${{ github.workspace }}/vcpkg"

jobs:
  analyze:
    name: Build with SCons
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Setup scons
        run: |
          python -m pip install scons
          scons --version

      - name: Get vcpkg
        run: |
          git clone -n https://github.com/microsoft/vcpkg
          cd vcpkg
          git checkout 2023.04.15
          .\bootstrap-vcpkg.bat

      - name: vcpkg install
        run: |
          cd gdext
          vcpkg install --triplet x64-windows-static-md

      - name: Build debug
        run: |
          cd gdext
          scons

      - name: Build release
        run: |
          cd gdext
          scons target=template_release
